### ISSUE TITLE
Namespace collision with collective.blog.portlets

### ISSUE THREAD

**Issue by djowett** [collective/collective.blog#1]
Doesn't play nicely - trying to install both (on Plone 5) & collective.blog.portlets gets hidden

**Comment by pcdummy** [comment]
They also aren't compatible with each other and c.blog.portlets is Plone 4.

**Comment by djowett** [comment]
c.blog.portlets could complement this product IMO.
And it could be P5 compatible - see work on [my branch](https://github.com/collective/collective.blog.portlets/tree/WIP-plone5-compat-using-z3c.form)

No worries, this isn't something I'm using at the moment, I went for `blog.post` instead at this time.
