### ISSUE TITLE
Blog / Blog Post / Blog Author

### ISSUE THREAD

**Issue by tisto** [collective/collective.blog#19]
@ericof @jonaspiterek I am skeptical about the "Blog" content object. For DLR/FZJ we will use a subsite or even a dedicated Plone instance for the blog. Therefore we just can not have a "Blog" content object that allows "post" and "author" to be added to this container. It could be an interface that we add to our "Subsite" content object or even "INavigationRoot". However, this is our main use case and needs to be taken into account here.

We also agreed with @davisagli that the right title for a blog post is "Blog Post" and we agreed to use "Blog Author". Please check the specs in our Trello card.

**Comment by davisagli** [comment]
My advice:
1. Create a "blog" behavior
2. Include a Blog content type in collective.blog which has that behavior enabled.
3. If a specific project has different needs, it can disable the Blog content type in its profile.

**Comment by ericof** [comment]
I agree with the Blog behavior approach and disabling the Blog content type in specific projects.
About the names, I would suggest we meet Author and Post as the content type names, but change it to Blog Author and Blog Post in the translations. This way we solve the UX problem but keep the filenames and fti shorter.

**Comment by ericof** [comment]
This issue will cover only the 'titles' of the content types. The #20 will take care of the blog behavior

**Comment by tisto** [comment]
@davisagli @ericof when you say "Blog Behavior", do you mean the existing "IBlog" interface? The only advantage of a behavior is that we can enable/disable it TTW.

**Comment by ericof** [comment]
The idea is to apply to other content types that would then behave like a Blog.
As I've said to you, we need something like that to be able to handle schema.org in a sane way and support some SEO enhancements (even though DLR and FZJ do not require that right now).

**Comment by tisto** [comment]
@ericof ok, got it. Though, I disagree with the naming. We should name things "Blog Author" and "Blog Post" both in the UI and in the code. We are not in the 80s any longer and developer approachability and consistent naming trumps the bytes our software consumes. :)

Anyways, @jonaspiterek should decide on this. It is his package...
