### ISSUE TITLE
Is the blog content text cannot be search?

### ISSUE THREAD

**Issue by mactrash** [collective/collective.blog#2]
Or I did something wrong?

**Comment by mactrash** [comment]
Sorry my fault, I need to do some more study

**Comment by mactrash** [comment]
Yes double checked, the body content text is not searchable. @pcdummy

**Comment by pcdummy** [comment]
Hmm the Text comes from the behaviour "plone.app.contenttypes.behaviors.richtext.IRichText".

Not sure howto make the searchable text indexer to index IRichText.

I ask in the chat, but i have to say that not using this anymore as i switched my Blog back to Hugo.

**Comment by mactrash** [comment]
Thanks for your reply, so i better don't use it since it will never got updates.
