### ISSUE TITLE
Affect other plone addon

### ISSUE THREAD

**Issue by mactrash** [collective/collective.blog#4]
Error with save in other addon.

Here is the full error message:

Display traceback as text

Traceback (innermost last):

Module ZPublisher.Publish, line 146, in publish
Module Zope2.App.startup, line 301, in commit
Module transaction._manager, line 89, in commit
Module transaction._transaction, line 329, in commit
Module transaction._transaction, line 443, in _commitResources
Module ZODB.Connection, line 567, in commit
Module ZODB.Connection, line 623, in _commit
Module ZODB.Connection, line 658, in _store_objects
Module ZODB.serialize, line 422, in serialize
Module ZODB.serialize, line 431, in _dump
PicklingError: Can't pickle <class 'blog.post.blog_post.IBlogPost'>: import of module blog.post.blog_post failed

**Comment by jonaspiterek** [comment]
Closing because of deprecation.
