### ISSUE TITLE
Is this the successor for collective.blog.*?

### ISSUE THREAD

**Issue by htgoebel** [collective/collective.blog#5]
Is this the (maybe inofficial) successor for collective.blog.{portlets,view,feeds,star}? If so, it would be great the readme could state this. Thanks.

**Comment by pcdummy** [comment]
Hi @htgoebel,

it could be a successor if I would have time to to improve it. But i stopped developing in Plone since some time.

If you want you can take over.

Kind regards,
René

**Comment by htgoebel** [comment]
After having a look at collective.blogging, I have the impression that collective.blogging is a more sophisticated approach: It extents all content types to become a "blog entry". I'd rather support the other project.

Anyway you could merge #6 :-)

**Comment by pcdummy** [comment]
Let's keep this ticket open so others know, think i gonna put a link in the README for it.

**Comment by jonaspiterek** [comment]
Taking over the development.
