### ISSUE TITLE
Cannot create any type of content if blog has no preview image

### ISSUE THREAD

**Issue by jonaspiterek** [collective/collective.blog#73]
When trying to create content in a `BlogFolder` without the `BlogFolder` having a preview image you get an `AttributeError` from `Module plone.volto.behaviors.preview_link, line 59, in __call__` saying `'NoneType' object has no attribute 'to_object'` but if the `BlogFolder` has a preview image everything works fine.

/cc @davisagli @ericof

**Comment by ericof** [comment]
@jonaspiterek This is related to this [PR](https://github.com/plone/plone.volto/pull/148). After the PR is merged, and a new plone.volto is released, we need to add plone.volto as a dependency here.
