### ISSUE TITLE
Test-suite fails

### ISSUE THREAD

**Issue by htgoebel** [collective/collective.blog#8]
The test-suite shows up errors which seem to be cause by errors in the test-suite itself, see [Travis-CI build #1 ](https://travis-ci.com/collective/collective.blog/builds/130631641).

Most obvious one is:
```
    from collective.blog.interfaces import IBlogEntry
ImportError: cannot import name IBlogEntry
```

**Comment by jonaspiterek** [comment]
Closing because of deprecation.
